[package]
name = "candy_machine"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosm-tome-wasm-deploy-fork = "0.1.0"
serde = "1.0"
serde_json = "1.0"
toml = "0.7.6"
serde_derive = "1.0.188"
tokio = { version = "1.12.0", features = ["full"] }