[network]
# grpc = "http://injective-grpc.polkachu.com:14390" 
grpc = "http://injective-testnet-grpc.polkachu.com:14390"
chain_id = "injective-888"
# chain_id = "injective-1" 

[auth]
mnemonic = "arrange cactus jewel fuel fantasy vote picture kitchen stand talk jelly foot"
address = "inj1s3hfffwfvehcmwxdltcmt5a4fntj4ytaqstxnr"

[contract]
admin = "inj1s3hfffwfvehcmwxdltcmt5a4fntj4ytaqstxnr"
code_id = 582 # 582 for testnet
max_supply = 5000
collection_name = "Nebula Test"
collection_symbol = "NEBULA"
collection_description = "The first nebula deployed contract"
collection_banner_uri = "YOUR_COLLECTION_BANNER_URI_HERE"
collection_pfp_uri = "YOUR_COLLECTION_PFP_URI_HERE"
collection_ext_uri = "YOUR_COLLECTION_EXT_URI_HERE"
royalty_bps = 100 
creators = [
    { address = "inj1s3hfffwfvehcmwxdltcmt5a4fntj4ytaqstxnr", share = 100 }
]
json = "contract.json"
contract_address = "inj1ngx4ls2z0yd0xremyzlyu9xha785f2h6l7ur0g"